In [2]:
#import dependencies
import pandas as pd

In [4]:
#read in csv files
april_2019 = pd.read_csv("data/201904-citibike-tripdata.csv")
may_2019 = pd.read_csv("data/201905-citibike-tripdata.csv")

In [5]:
#preview data
may_2019.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,139,00:01.9,02:21.5,447,8 Ave & W 52 St,40.763707,-73.985162,423,W 54 St & 9 Ave,40.765849,-73.986905,31170,Subscriber,1983,1
1,754,00:03.0,12:37.7,3258,W 27 St & 10 Ave,40.750182,-74.002184,3255,8 Ave & W 31 St,40.750585,-73.994685,25560,Customer,1969,0
2,2308,00:04.6,38:33.2,3093,N 6 St & Bedford Ave,40.717452,-73.958509,3676,Van Brunt St & Van Dyke St,40.675833,-74.014726,33369,Subscriber,1978,1
3,143,00:19.3,02:42.5,3486,Schermerhorn St & Bond St,40.688417,-73.984517,3412,Pacific St & Nevins St,40.685376,-73.983021,32041,Subscriber,1997,1
4,138,00:22.2,02:40.6,388,W 26 St & 10 Ave,40.749718,-74.002950,494,W 26 St & 8 Ave,40.747348,-73.997236,35237,Subscriber,1967,1

In [6]:
#create data frames
may2019_df = pd.DataFrame(may_2019)
april2019_df = pd.DataFrame(april_2019)
may2019_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,139,00:01.9,02:21.5,447,8 Ave & W 52 St,40.763707,-73.985162,423,W 54 St & 9 Ave,40.765849,-73.986905,31170,Subscriber,1983,1
1,754,00:03.0,12:37.7,3258,W 27 St & 10 Ave,40.750182,-74.002184,3255,8 Ave & W 31 St,40.750585,-73.994685,25560,Customer,1969,0
2,2308,00:04.6,38:33.2,3093,N 6 St & Bedford Ave,40.717452,-73.958509,3676,Van Brunt St & Van Dyke St,40.675833,-74.014726,33369,Subscriber,1978,1
3,143,00:19.3,02:42.5,3486,Schermerhorn St & Bond St,40.688417,-73.984517,3412,Pacific St & Nevins St,40.685376,-73.983021,32041,Subscriber,1997,1
4,138,00:22.2,02:40.6,388,W 26 St & 10 Ave,40.749718,-74.002950,494,W 26 St & 8 Ave,40.747348,-73.997236,35237,Subscriber,1967,1

In [ ]:
#merge data from both frames and preview
merged2019 = pd.merge(april2019_df, may2019_df, on= "start station id", how = "inner")
merged2019.head()

In [ ]:
#check data types for the frame
merged2019.type()

In [ ]:
#export cleaned csv
merged2019.to_csv(r'/data/cleaned-2019.csv', index=False)